version: "3"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_CORS_ORIGIN=http://localhost:8000,http://127.0.0.1:8000,file://
      - N8N_CORS_CREDENTIALS=true
      # - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - TZ=America/Sao_Paulo
    volumes:
      - ./n8n_data:/home/node/.n8n
